apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-web-app
  name: my-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-web-app
    spec:
      containers:
      - image: ravish/web-hello:latest
        name: web-hello
        ports:
        - containerPort: 5000
        resources: {}
status: {}
