apiVersion: v1
kind: Service
metadata:
name: my-web-app-svc
labels:
  app: my-web-app
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: my-web-app
  tier: my-web-app
type: LoadBalancer
